### ISSUE TITLE
Hamburger button no longer animates after the transition to SASS

### ISSUE THREAD

**Issue by adamthebig** [picdorsey/frunt#1]
Also, do we need the animate.scss file if we are using autoprefixer?

**Comment by tylodo** [comment]
I only really use the `animation` mixin in that file. The other ones are kinda pointless now with the autoprefixer.

I also noticed the entire slider isn't working on mobile.

**Comment by adamthebig** [comment]
Okay, got it. I just wanted to make sure I was understanding autoprefixer
fully before removing some stuff.

I think I just need to add some mobile defaults for the slider. I'll take a
peak.

On Sun, Jan 18, 2015 at 5:29 PM, tylodo <notifications@github.com> wrote:

> I only really use the animation mixin in that file. The other ones are
> kinda pointless now with the autoprefixer.
>
> I also noticed the entire slider isn't working on mobile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/picdorsey/frunt/issues/1#issuecomment-70429539>.
>



-- 
*ADAM DORSEY*
Partner


[image: picdorsey.com]
<http://picdorsey.com/?utm_source=email%20signature&utm_medium=email&utm_content=homepage&utm_campaign=daily%20email%20logo>


502 Rock Spring Road
Bel Air, Maryland 21014
410.879.6780 x102
picdorsey.com
<http://picdorsey.com/?utm_source=email%20signature&utm_medium=email&utm_content=homepage&utm_campaign=daily%20email%20link>
