### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by adamthebig** [picdorsey/frunt#2]
@tylodo I'd like to make the argument for a more robust .gitignore file for Frunt.

I know you like the clean version and to globally ignore system junk, etc.

I think most people won't be doing that, that is more of an advanced user thing.

Bootstrap uses:

```
# Ignore docs files
_gh_pages
_site
.ruby-version

# Numerous always-ignore extensions
*.diff
*.err
*.log
*.orig
*.rej
*.swo
*.swp
*.vi
*.zip
*~

# OS or Editor folders
._*
.cache
.DS_Store
.idea
.project
.settings
.tmproj
*.esproj
*.sublime-project
*.sublime-workspace
nbproject
Thumbs.db

# Folders to ignore
bower_components
node_modules
.sass-cache
```

And we could add EE specifics or craft specifics for those repos:

```
# ExpressionEngine Cache & MinimEE Cache
_ee/expressionengine/cache/
```

**Comment by tylodo** [comment]
I'm down. I think you we should do

```
# ExpressionEngine Cache & MinimEE Cache
_ee/expressionengine/cache/*
!_ee/expressionengine/cache/.gitkeep
```

so the cache folder will still be their so when it's deployed.

**Comment by adamthebig** [comment]
Awesome.

On Fri, May 29, 2015 at 11:50 AM, tylodo <notifications@github.com> wrote:

> I'm down. I think you we should do
>
> # ExpressionEngine Cache & MinimEE Cache
> _ee/expressionengine/cache/*
> !_ee/expressionengine/cache/.gitkeep
>
> so the cache folder will still be their so when it's deployed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/picdorsey/Frunt/issues/2#issuecomment-106854240>.
>



-- 
*ADAM DORSEY*
Partner


[image: picdorsey.com]
<http://picdorsey.com/?utm_source=email%20signature&utm_medium=email&utm_content=homepage&utm_campaign=daily%20email%20logo>


502 Rock Spring Road
Bel Air, Maryland 21014
410.879.6780 x102
picdorsey.com
<http://picdorsey.com/?utm_source=email%20signature&utm_medium=email&utm_content=homepage&utm_campaign=daily%20email%20link>

**Comment by tylodo** [comment]
Just a note about this repo:

I'm using this: https://github.com/boennemann/semantic-release

to set the versions automatically and to publish to NPM and Github after every push to Master. When you make commits use the Angular commit syntax so the versions can be detected correctly.

https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit

**Comment by adamthebig** [comment]
Hopefully I did this right:
a624dc77bb743f026e9ed71e6cbaf2c9898ae28d

**Comment by tylodo** [comment]
Looks good. My deployment hook broke because I accidentally renamed the Repository with a capital "F" instead of a lowercase one. Next push will deploy the code.
