### ISSUE TITLE
Normalize and Reboot

### ISSUE THREAD

**Issue by adamthebig** [picdorsey/frunt#3]
@TylerODonnell This reads like normalize was built into the reboot:
http://v4-alpha.getbootstrap.com/content/reboot/

And the comment in reboot file:

```
// Reboot
//
// Global resets to common HTML elements and more for easier usage by Bootstrap.
// Adds additional rules on top of Normalize.css, including several overrides.
```

If that is the case, I'll just remove normalize and use reboot to get rid of some kilobytes.

**Comment by tylerodonnell** [comment]
They still use normalize for majority of the work.

I just grabbed what they had in their  `reboot` file.

```
// Bootstrap Reboot only
//
// Includes only Normalize and our custom Reboot reset.

@import "variables";
@import "mixins/hover";
@import "mixins/tab-focus";

@import "normalize";
@import "reboot";
```

**Comment by adamthebig** [comment]
Okay, gotcha.

On Fri, Sep 11, 2015 at 4:42 PM, TylerODonnell notifications@github.com
wrote:

> They still use normalize for majority of the work.
> 
> I just grabbed what they had in their reboot file.
> 
> // Bootstrap Reboot only
> //
> // Includes only Normalize and our custom Reboot reset.
> 
> @import "variables";
> @import "mixins/hover";
> @import "mixins/tab-focus";
> 
> @import "normalize";
> @import "reboot";
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/picdorsey/frunt/issues/3#issuecomment-139657109.

## 

_ADAM DORSEY_
Partner

[image: picdorsey.com]
http://picdorsey.com/?utm_source=email%20signature&utm_medium=email&utm_content=homepage&utm_campaign=daily%20email%20logo

502 Rock Spring Road
Bel Air, Maryland 21014
410.879.6780 x102
picdorsey.com
http://picdorsey.com/?utm_source=email%20signature&utm_medium=email&utm_content=homepage&utm_campaign=daily%20email%20link
